return {
	{
		"stevearc/aerial.nvim",
		dependencies = {
			"nvim-treesitter/nvim-treesitter",
			"nvim-tree/nvim-web-devicons",
		},
		cmd = { "AerialToggle", "AerialOpen", "AerialNavToggle" },
		keys = {
			{ "<leader>o", "<cmd>AerialToggle<cr>", desc = "Toggle Code Outline (Functions & Classes)" },
			{ "<leader>co", "<cmd>AerialToggle<cr>", desc = "Toggle Code Outline (Functions & Classes)" },
			{ "<leader>O", "<cmd>AerialNavToggle<cr>", desc = "Navigate Symbols in Floating Window" },
		},
		opts = {
			backends = { "lsp", "treesitter", "markdown", "man" },
			layout = {
				max_width = { 40, 0.25 },
				width = 32,
				min_width = 25,
				default_direction = "right",
				placement = "window",
				resize_to_content = false,
			},
			attach_mode = "global",
			close_automatic_events = {},
			keymaps = {
				["?"] = "actions.show_help",
				["g?"] = "actions.show_help",
				["<CR>"] = "actions.jump",
				["<2-LeftMouse>"] = "actions.jump",
				["<C-v>"] = "actions.jump_vsplit",
				["<C-s>"] = "actions.jump_split",
				["p"] = "actions.scroll",
				["<C-j>"] = "actions.down_and_scroll",
				["<C-k>"] = "actions.up_and_scroll",
				["{"] = "actions.prev",
				["}"] = "actions.next",
				["[["] = "actions.prev_up",
				["]]"] = "actions.next_up",
				["q"] = "actions.close",
				["o"] = "actions.tree_toggle",
				["za"] = "actions.tree_toggle",
				["O"] = "actions.tree_toggle_recursive",
				["zA"] = "actions.tree_toggle_recursive",
				["l"] = "actions.tree_open",
				["zo"] = "actions.tree_open",
				["L"] = "actions.tree_open_recursive",
				["zO"] = "actions.tree_open_recursive",
				["h"] = "actions.tree_close",
				["zc"] = "actions.tree_close",
				["H"] = "actions.tree_close_recursive",
				["zC"] = "actions.tree_close_recursive",
				["zr"] = "actions.tree_increase_fold_level",
				["zR"] = "actions.tree_open_all",
				["zm"] = "actions.tree_decrease_fold_level",
				["zM"] = "actions.tree_close_all",
				["zx"] = "actions.tree_sync_folds",
				["zX"] = "actions.tree_sync_folds",
			},
			filter_kind = {
				"Class",
				"Constructor",
				"Enum",
				"Function",
				"Interface",
				"Module",
				"Method",
				"Struct",
			},
			icons = {
				Array = "󱡠 ",
				Boolean = "󰨙 ",
				Class = "󰠱 ",
				Constant = "󰏿 ",
				Constructor = " ",
				Enum = " ",
				EnumMember = " ",
				Event = " ",
				Field = "󰜢 ",
				File = "󰈙 ",
				Function = "󰊕 ",
				Interface = " ",
				Key = "󰌆 ",
				Method = "󰊕 ",
				Module = " ",
				Namespace = "󰦮 ",
				Null = "󰟢 ",
				Number = "󰎠 ",
				Object = "󰅩 ",
				Operator = "󰆕 ",
				Package = " ",
				Property = " ",
				String = "󰅳 ",
				Struct = "󰆼 ",
				TypeParameter = "󰗴 ",
				Variable = "󰀫 ",
			},
			show_guides = true,
		},
	},
}
