return {
	{
		"xeluxee/competitest.nvim",
		dependencies = { "MunifTanjim/nui.nvim" },
		cmd = { "CompetiTest" },
		keys = {
			{ "<leader>tr", "<cmd>CompetiTest run<cr>", desc = "Run All Test Cases (Codeforces/AtCoder)" },
			{ "<leader>ta", "<cmd>CompetiTest add_testcase<cr>", desc = "Add New Test Case" },
			{ "<leader>te", "<cmd>CompetiTest edit_testcase<cr>", desc = "Edit Test Case" },
			{ "<leader>td", "<cmd>CompetiTest delete_testcase<cr>", desc = "Delete Test Case" },
			{ "<leader>tp", "<cmd>CompetiTest receive problem<cr>", desc = "Receive Problem from Browser" },
			{ "<leader>tc", "<cmd>CompetiTest receive contest<cr>", desc = "Receive Entire Contest from Browser" },
			{ "<leader>tu", "<cmd>CompetiTest show_ui<cr>", desc = "Show / Toggle Test UI" },
		},
		opts = {
			compile_directory = ".",
			compile_command = {
				c = { exec = "gcc", args = { "-Wall", "$(FNAME)", "-o", "$(FNOEXT)" } },
				cpp = { exec = "g++", args = { "-std=c++20", "-Wall", "-O2", "$(FNAME)", "-o", "$(FNOEXT)" } },
				rust = { exec = "rustc", args = { "$(FNAME)" } },
			},
			run_command = {
				c = { exec = "./$(FNOEXT)" },
				cpp = { exec = "./$(FNOEXT)" },
				rust = { exec = "./$(FNOEXT)" },
				python = { exec = "python3", args = { "$(FNAME)" } },
			},
			testcases_directory = ".",
			testcases_use_single_file = false,
			testcases_auto_detect_storage = true,
			testcases_single_file_format = "$(FNOEXT).testcases",
			testcases_input_file_format = "$(FNOEXT)_input$(TCNUM).txt",
			testcases_output_file_format = "$(FNOEXT)_output$(TCNUM).txt",
			companion_port = 27121,
			receive_print_message = true,
			save_current_file = true,
			save_all_files = false,
			runner_ui = {
				interface = "split",
				selector_show_diff = true,
				show_nu = true,
				show_rnu = false,
				mappings = {
					run_again = "r",
					run_all_again = "R",
					kill = "K",
					kill_all = "<C-k>",
					view_input = "i",
					view_output = "a",
					view_stdout = "o",
					view_stderr = "e",
					toggle_diff = "d",
					close = { "q", "<Esc>" },
				},
			},
			popup_ui = {
				total_width = 0.8,
				total_height = 0.8,
				layout = {
					{ 1, "tc" },
					{ 1, { { 1, "so" }, { 1, "si" } } },
					{ 1, { { 1, "eo" }, { 1, "se" } } },
				},
			},
			view_output_diff = true,
		},
	},
}
